AWSTemplateFormatVersion: '2010-09-09'
Description: Retail CSV Pipeline - Clean and Convert CSV to Parquet

Parameters:
  InputBucket:
    Type: String
  OutputBucket:
    Type: String
  LambdaS3Key:
    Type: String

Resources:
  CsvTransformerFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: retail-csv-transformer
      Handler: transform_and_store.lambda_handler
      Runtime: python3.9
      Timeout: 300
      Role: arn:aws:iam::025066276495:role/MyLambdaExecutionRole
      Code:
        S3Bucket: !Ref InputBucket
        S3Key: !Ref LambdaS3Key
      Environment:
        Variables:
          OUTPUT_BUCKET: !Ref OutputBucket

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref CsvTransformerFunction
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub arn:aws:s3:::${InputBucket}

Outputs:
  LambdaFunctionArn:
    Description: ARN of the Lambda function
    Value: !GetAtt CsvTransformerFunction.Arn
